name: main

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-2019

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

#    - name: Restore Packages
#      run: nuget restore MySolution.sln

    - name: Build solution
      run: msbuild DiskSpace-Examiner.sln -t:rebuild -property:Configuration=Release
